language: python

python:
    - 3.4

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - conda install --yes pytest

install:
    - echo "This should be avoided in the future"
    - sudo apt-get install -qq liblapack-dev libblas-dev libatlas-dev
    - ln -s /usr/lib/libblas.so libf77blas.so.3
    - conda install --yes -c gimli pygimli
    - ls /home/travis/miniconda3/lib
    - ls /usr/lib
    - ls /usr/local/lib
    - echo $PATH
    - echo $LD_LIBRARY_PATH

script:
    - python -c "import pygimli; pygimli.test()"
