language: python

python:
    - 3.4

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - conda install --yes pytest

install:
    - sudo apt-get install libblas-all-dev liblapack-all-dev libatlas-dev # this should be avoided in the future
    - conda install --yes -c gimli pygimli

script:
    - python -c "import pygimli; pygimli.test()"
