package:
    name: pygimli
    version: 1.1rc

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    rpaths:
        - lib/
        - lib64/

source:
    # git_url: https://github.com/gimli-org/gimli.git
    #git_tag: dev # build from dev branch
    path: /home/fwagner/src/gimli/gimli

requirements:
    build:
        - gcc >=4.7
        - cmake >=2.8.10
        - python
        - boost ==1.61
        - numpy >=1.10
        - openblas
        #- suitesparse

    run:
        - libgcc
        - python
        - boost ==1.61
        - numpy >=1.10
        - pyqt ==4.11.4 # https://github.com/ContinuumIO/anaconda-issues/issues/1068
        - matplotlib
        - openblas
        - scipy # for workshop only
        #- suitesparse

test:
    imports:
        - pygimli
    commands:
        # - harmfit -h # C++ app
        - pytripatch -h # Python app

about:
    home: http://www.pygimli.org
    summary: Geophysical Inversion and Modelling Library
    license: Apache 2.0
