package:
  name: pygimli
  version: 1.0rc

source:
    #git_url: git@github.com:gimli-org/gimli.git
    #svn_url: http://svn.code.sf.net/p/libgimli/code/trunk
    path: ../../../src/gimli/trunk

requirements:
    build:
        - gcc >=4.7
        - cmake >=2.8.10
        - python >=3.3
        - boost ==1.56.0
        - numpy >=1.8
        - suitesparse

    run:
        - python
        - boost ==1.56.0
        - numpy >=1.8
        - matplotlib >=1.3.0 # make optional
        - scipy # make optional

#test:
    #imports:
        #- pygimli
    #commands:
        #- harmfit -h # C++ app
        #- pytripatch -h # Python app

about:
    home: http://www.pygimli.org
    summary: Geophysical Inversion and Modelling Library
    license: GNU Lesser General Public License (LGPL)
