package:
    name: pybert
    version: 2.1.0

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    #git_url: https://github.com/gimli-org/gimli.git
    #git_tag: dev # build from dev branch
    path: /home/wagner/git/bert/trunk

requirements:
    build:
        - gcc >=4.7
        - cmake >=2.8.10
        - python
        - boost ==1.60
        - numpy >=1.10
        - openblas
        #- suitesparse
        #- metis

    run:
        - pygimli
        - python
        - boost ==1.60
        - numpy >=1.10
        - matplotlib >=1.3.0 # make optional
        - pyqt <=4.11.4
        - qt <=4.8.7
        - openblas
        - scipy # for workshop only
        #- suitesparse

test:
    imports:
        - pybert
    commands:
        - dcinv -h

about:
    home: http://www.resistivity.net
    summary: Boundless Electrical Resistivity Tomography
