package:
    name: pybert
    version: 2.2.0

build:
    number: 2

source:
    #git_url: https://github.com/gimli-org/gimli.git
    #git_tag: dev # build from dev branch
    path: /home/wagner/git/bert/trunk

requirements:
    build:
        - pygimli
        - python

    run:
        - pygimli
        - python
        - tetgen

test:
    imports:
      - pybert
    commands:
      - dcinv -h

about:
    home: http://www.resistivity.net
    summary: Boundless Electrical Resistivity Tomography
